stages:
  preprocess:
    cmd: python src/preprocessing.py
    deps:
    - data/raw/TelcoCustomer_Churn.csv
    - src/preprocessing.py
    outs:
    - data/processed/train.csv
  tune:
    cmd: python src/tune.py
    deps:
    - data/processed/train.csv
    - src/tune.py
    outs:
    - models/best_model.pkl
    - models/features.pkl
